### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by starfishmod** [davidmoreno/aseqrc#1]
I tried running this, but wasn't sure how to install appropriate libs or which command to use.
Thanks

**Comment by davidmoreno** [comment]
Easier way is to use `make deb` which generates a deb file. If not, check other make options.

When I have some time I will add the appropriate section to the README.

**Comment by davidmoreno** [comment]
Added pacakges, more instructions, and some fixes.

Also improved README so you know what you will get. :)

Enjoy!

**Comment by starfishmod** [comment]
FYI: I got this running on Ubuntu 18.04 but I had to install python3-pyalsa manually from here:
https://launchpad.net/ubuntu/disco/amd64/python3-pyalsa/1.1.6-1build1

Now works great - thanks!
